name: Build & Distribute Snapdex (Compose)

on:
  push:
    branches: [ main ]
    paths:
      - 'Snapdex-Compose/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Distribute AAB

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Create signing.properties
        run: |
          echo "storeFile=../keystore.jks" > Snapdex-Compose/signing.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> Snapdex-Compose/signing.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> Snapdex-Compose/signing.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> Snapdex-Compose/signing.properties

      - name: Grant execute permission
        run: chmod +x ./Snapdex-Compose/gradlew

      - name: Run init script
        run: dotnet fsi Init.fsx

      - name: Build Release AAB
        working-directory: ./Snapdex-Compose
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Snapdex-AAB
          path: Snapdex-Compose/app/build/outputs/bundle/release/app-release.aab

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          curl -sL https://firebase.tools | bash
          ./firebase appdistribution:distribute Snapdex-Compose/app/build/outputs/bundle/release/app-release.aab \
            --app snapdex-64209 \
            --groups testers \
            --release-notes "Automated build from GitHub Actions"

      #- name: Decode Google Play service account
      #  run: |
      #    echo "${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}" | base64 -d > service-account.json
      #
      #- name: Publish to Play Store
      #  uses: r0adkll/upload-google-play@v1
      #  with:
      #    serviceAccountJson: service-account.json
      #    packageName: com.yourcompany.snapdex
      #    releaseFiles: Snapdex-Compose/app/build/outputs/bundle/release/app-release.aab
      #    track: production
      #    status: completed
